eureka:
  client:
    service-url:
      defaultZone: http://kejun1.com:81/eureka/,http://kejun2.com:82/eureka/

server:
  port: 83

spring:
  application:
    name: User-Consumer

feign:
  client:
    config:
      service-valuation:
        request-interceptors:
        - com.unyoah.userconsumer.MyBasicAuthRequestInterceptor
  hystrix:
    enabled: true

logging:
  level:
    com:
      unyoah:
        userconsumer: debug

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE