eureka:
  client:
    service-url:
      defaultZone: http://kejun1.com:81/eureka/,http://kejun2.com:82/eureka/
server:
  port: 84

spring:
  application:
    name: User-Provider
  security:
    user:
      name: root
      password: root